# docker-compose up -d

version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U ${DB_USER} -d ${DB_NAME} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env 
    container_name: lab7_api
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: lab7_web
    depends_on:
      - api
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app
      - ./web/templates:/app/templates
  